// services/vendingMachine.service.ts
import { Machine } from "../models/VM.model";

export class MachineService {
  // ========== MACHINE SERVICES ==========

  static async createMachine(machineData: any) {
    const machine = new Machine(machineData);
    return await machine.save();
  }

  static async getAllMachines() {
    return await Machine.find().sort({ createdAt: -1 });
  }

  static async getMachineById(machineId: string) {
    return await Machine.findById(machineId);
  }

  static async updateMachine(machineId: string, updateData: any) {
    return await Machine.findByIdAndUpdate(machineId, updateData, {
      new: true,
      runValidators: true,
    });
  }

  static async deleteMachine(machineId: string) {
    return await Machine.findByIdAndDelete(machineId);
  }

  static async updateMachineStatus(machineId: string, statusData: any) {
    return await Machine.findByIdAndUpdate(machineId, statusData, { new: true });
  }

  // ========== RACK SERVICES ==========

  static async addRacks(
    machineId: string,
    racksData: Array<{ slots: number; capacity: number; rackName?: string }>
  ) {
    const machine = await Machine.findById(machineId);
    if (!machine) {
      throw new Error("Machine not found");
    }

    // Get existing racks count for auto-naming
    const existingRacksCount = machine.racks?.length || 0;

    // Prepare racks to add
    const racksToAdd = racksData.map((rack, index) => ({
      rackName: rack.rackName || String.fromCharCode(65 + existingRacksCount + index),
      slots: rack.slots,
      capacity: rack.capacity,
      slotsList: [], // Will be auto-generated by pre-save middleware
    }));

    // Validate unique rack names
    for (const newRack of racksToAdd) {
      const existingRack = machine.racks.find((rack: any) => rack.rackName === newRack.rackName);
      if (existingRack) {
        throw new Error(`Rack with name "${newRack.rackName}" already exists`);
      }
    }

    // Add racks to machine
    machine.racks.push(...racksToAdd);
    await machine.save();

    // Return the newly added racks with slots
    const addedRacks = machine.racks.slice(-racksToAdd.length);
    return addedRacks.map((rack: any) => ({
      id: rack._id,
      name: rack.rackName,
      slots: rack.slots,
      capacity: rack.capacity,
      slotsList: rack.slotsList.map((slot: any) => ({
        id: slot._id,
        slotNumber: slot.slotNumber,
        status: slot.status,
      })),
    }));
  }

  static async getMachineRacks(machineId: string) {
    const machine = await Machine.findById(machineId);
    if (!machine) return [];

    return machine.racks.map((rack: any) => ({
      id: rack._id,
      name: rack.rackName,
      slots: rack.slots,
      capacity: rack.capacity,
      slotsList: rack.slotsList.map((slot: any) => ({
        id: slot._id,
        slotNumber: slot.slotNumber,
        status: slot.status,
        productId: slot.productId,
        productName: slot.productName,
        price: slot.price,
        expiryDate: slot.expiryDate,
      })),
    }));
  }

  static async getRackById(rackId: string) {
    const machine = await Machine.findOne({ "racks._id": rackId });
    if (!machine) return null;

    const rack = machine.racks.id(rackId);
    if (!rack) return null;

    return {
      id: rack._id,
      name: rack.rackName,
      slots: rack.slots,
      capacity: rack.capacity,
      slotsList: rack.slotsList.map((slot: any) => ({
        id: slot._id,
        slotNumber: slot.slotNumber,
        status: slot.status,
        productId: slot.productId,
        productName: slot.productName,
        price: slot.price,
        expiryDate: slot.expiryDate,
      })),
      machineId: machine._id,
    };
  }

  static async updateRack(rackId: string, updateData: any) {
    const machine = await Machine.findOne({ "racks._id": rackId });
    if (!machine) return null;

    const rack = machine.racks.id(rackId);
    if (!rack) return null;

    // Update rack fields
    if (updateData.rackName) rack.rackName = updateData.rackName;
    if (updateData.slots !== undefined) {
      rack.slots = updateData.slots;
      // SlotsList will be regenerated by pre-save middleware
    }
    if (updateData.capacity !== undefined) rack.capacity = updateData.capacity;

    await machine.save();

    return {
      id: rack._id,
      name: rack.rackName,
      slots: rack.slots,
      capacity: rack.capacity,
      slotsList: rack.slotsList.map((slot: any) => ({
        id: slot._id,
        slotNumber: slot.slotNumber,
        status: slot.status,
      })),
      machineId: machine._id,
    };
  }

  static async deleteRack(rackId: string) {
    const machine = await Machine.findOne({ "racks._id": rackId });
    if (!machine) return null;

    const rack = machine.racks.id(rackId);
    if (!rack) return null;

    // Remove rack
    machine.racks.pull(rack._id as any);
    await machine.save();

    return rack;
  }

  static async deleteAllMachineRacks(machineId: string) {
    const machine = await Machine.findById(machineId);
    if (!machine) return null;

    machine.racks.splice(0, machine.racks.length);
    await machine.save();

    return machine;
  }

  // ========== SLOT SERVICES ==========

  static async getMachineSlots(machineId: string) {
    const machine = await Machine.findById(machineId);
    if (!machine) return [];

    const allSlots: any[] = [];
    machine.racks.forEach((rack: any) => {
      rack.slotsList.forEach((slot: any) => {
        allSlots.push({
          id: slot._id,
          rackId: rack._id,
          rackName: rack.rackName,
          slotNumber: slot.slotNumber,
          status: slot.status,
          productId: slot.productId,
          productName: slot.productName,
          price: slot.price,
          expiryDate: slot.expiryDate,
        });
      });
    });

    return allSlots;
  }

  static async getSlotById(slotId: string) {
    const machine = await Machine.findOne({ "racks.slotsList._id": slotId });
    if (!machine) return null;

    let foundSlot = null;
    let foundRack = null;

    for (const rack of machine.racks) {
      const slot = rack.slotsList.id(slotId);
      if (slot) {
        foundSlot = slot;
        foundRack = rack;
        break;
      }
    }

    if (!foundSlot) return null;

    return {
      id: foundSlot._id,
      rackId: foundRack?._id,
      rackName: foundRack?.rackName,
      slotNumber: foundSlot.slotNumber,
      status: foundSlot.status,
      productId: foundSlot.productId,
      productName: foundSlot.productName,
      price: foundSlot.price,
      expiryDate: foundSlot.expiryDate,
      machineId: machine._id,
    };
  }

  static async occupySlot(
    slotId: string,
    productData: {
      productId: string;
      productName: string;
      price: number;
      expiryDate?: Date;
    }
  ) {
    const machine = await Machine.findOne({ "racks.slotsList._id": slotId });
    if (!machine) throw new Error("Slot not found");

    let foundSlot = null;
    let foundRack = null;

    for (const rack of machine.racks) {
      const slot = rack.slotsList.id(slotId);
      if (slot) {
        foundSlot = slot;
        foundRack = rack;
        break;
      }
    }

    if (!foundSlot) throw new Error("Slot not found");
    if (foundSlot.status === "occupied") {
      throw new Error("Slot is already occupied");
    }

    foundSlot.status = "occupied";
    foundSlot.productId = productData.productId;
    foundSlot.productName = productData.productName;
    foundSlot.price = productData.price;
    if (productData.expiryDate) {
      foundSlot.expiryDate = productData.expiryDate;
    }

    await machine.save();

    return {
      id: foundSlot._id,
      rackId: foundRack?._id,
      rackName: foundRack?.rackName,
      slotNumber: foundSlot.slotNumber,
      status: foundSlot.status,
      productId: foundSlot.productId,
      productName: foundSlot.productName,
      price: foundSlot.price,
      expiryDate: foundSlot.expiryDate,
    };
  }

  static async freeSlot(slotId: string) {
    const machine = await Machine.findOne({ "racks.slotsList._id": slotId });
    if (!machine) throw new Error("Slot not found");

    let foundSlot = null;

    for (const rack of machine.racks) {
      const slot = rack.slotsList.id(slotId);
      if (slot) {
        foundSlot = slot;
        break;
      }
    }

    if (!foundSlot) throw new Error("Slot not found");

    foundSlot.status = "available";
    foundSlot.productId = undefined;
    foundSlot.productName = undefined;
    foundSlot.price = undefined;
    foundSlot.expiryDate = undefined;

    await machine.save();

    return {
      id: foundSlot._id,
      slotNumber: foundSlot.slotNumber,
      status: foundSlot.status,
    };
  }

  static async updateSlotStatus(slotId: string, status: "available" | "occupied" | "maintenance") {
    const machine = await Machine.findOne({ "racks.slotsList._id": slotId });
    if (!machine) throw new Error("Slot not found");

    let foundSlot = null;

    for (const rack of machine.racks) {
      const slot = rack.slotsList.id(slotId);
      if (slot) {
        foundSlot = slot;
        break;
      }
    }

    if (!foundSlot) throw new Error("Slot not found");

    foundSlot.status = status;

    // If status is not occupied, clear product data
    if (status !== "occupied") {
      foundSlot.productId = undefined;
      foundSlot.productName = undefined;
      foundSlot.price = undefined;
      foundSlot.expiryDate = undefined;
    }

    await machine.save();

    return {
      id: foundSlot._id,
      slotNumber: foundSlot.slotNumber,
      status: foundSlot.status,
    };
  }

  // ========== COMBINED SERVICES ==========

  static async getMachineWithRacks(machineId: string) {
    const machine = await Machine.findById(machineId);
    if (!machine) {
      return { machine: null, racks: [], totalRacks: 0 };
    }

    const racks = machine.racks.map((rack: any) => ({
      id: rack._id,
      name: rack.rackName,
      slots: rack.slots,
      capacity: rack.capacity,
      slotsList: rack.slotsList.map((slot: any) => ({
        id: slot._id,
        slotNumber: slot.slotNumber,
        status: slot.status,
        productId: slot.productId,
        productName: slot.productName,
        price: slot.price,
      })),
    }));

    return {
      machine: {
        id: machine._id,
        machineId: machine.machineId,
        serialNumber: machine.serialNumber,
        modelNumber: machine.modelNumber,
        machineType: machine.machineType,
        firmwareVersion: machine.firmwareVersion,
        dimensions: {
          height: machine.height,
          width: machine.width,
          length: machine.length,
        },
        status: {
          door: machine.doorStatus,
          connectivity: machine.connectivityStatus,
          machine: machine.machineStatus,
          maintenance: machine.underMaintenance,
          decommissioned: machine.decommissioned,
        },
        internalTemperature: machine.internalTemperature,
      },
      racks: racks,
      totalRacks: racks.length,
    };
  }

  // ========== ADDITIONAL UTILITY SERVICES ==========

  static async getMachinesByType(machineType: string) {
    return await Machine.find({ machineType, decommissioned: "no" }).sort({ createdAt: -1 });
  }

  static async getActiveMachines() {
    return await Machine.find({
      machineStatus: "active",
      decommissioned: "no",
    }).sort({ createdAt: -1 });
  }

  static async updateRacksBatch(
    machineId: string,
    racksData: Array<{ rackId?: string; rackName: string; slots: number; capacity: number }>
  ) {
    const machine = await Machine.findById(machineId);
    if (!machine) throw new Error("Machine not found");

    // Process updates
    for (const rackData of racksData) {
      if (rackData.rackId) {
        // Update existing rack
        const rack = machine.racks.id(rackData.rackId);
        if (rack) {
          rack.rackName = rackData.rackName;
          if (rack.slots !== rackData.slots) {
            rack.slots = rackData.slots;
            // SlotsList will be regenerated by pre-save middleware
          }
          rack.capacity = rackData.capacity;
        }
      } else {
        // Add new rack
        machine.racks.push({
          rackName: rackData.rackName,
          slots: rackData.slots,
          capacity: rackData.capacity,
          slotsList: [],
        });
      }
    }

    await machine.save();

    return machine.racks.map((rack: any) => ({
      id: rack._id,
      name: rack.rackName,
      slots: rack.slots,
      capacity: rack.capacity,
      slotsCount: rack.slotsList.length,
    }));
  }

  static async getAvailableSlots(machineId: string) {
    const machine = await Machine.findById(machineId);
    if (!machine) return [];

    const availableSlots: any[] = [];
    machine.racks.forEach((rack: any) => {
      rack.slotsList.forEach((slot: any) => {
        if (slot.status === "available") {
          availableSlots.push({
            id: slot._id,
            rackId: rack._id,
            rackName: rack.rackName,
            slotNumber: slot.slotNumber,
          });
        }
      });
    });

    return availableSlots;
  }

  static async getOccupiedSlots(machineId: string) {
    const machine = await Machine.findById(machineId);
    if (!machine) return [];

    const occupiedSlots: any[] = [];
    machine.racks.forEach((rack: any) => {
      rack.slotsList.forEach((slot: any) => {
        if (slot.status === "occupied") {
          occupiedSlots.push({
            id: slot._id,
            rackId: rack._id,
            rackName: rack.rackName,
            slotNumber: slot.slotNumber,
            productId: slot.productId,
            productName: slot.productName,
            price: slot.price,
            expiryDate: slot.expiryDate,
          });
        }
      });
    });

    return occupiedSlots;
  }
}
